In [12]:
# 【課題】NumPyで配列の操作や演算をしよう

import numpy as np
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])
matrix_product = np.dot(A,B)

print(matrix_product)

print(matrix_product.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
